const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirt',
            category:'Shirts',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:100,
            brand:'Adidas',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Gucci Shirt',
            category:'Shirts',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:200,
            brand:'Gucci',
            rating:5.0,
            numReviews:15,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Balenciaga',
            category:'Shoes',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:120,
            brand:'Balenciaga',
            rating:5.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Puma Shirt',
            category:'Shirts',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:130,
            brand:'Puma',
            rating:3.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Gigi Shirt',
            category:'Shirts',
            image:'images/street-bunda-volcom-throback-ins-jacket-black.jpg',
            price:250,
            brand:'Gigi',
            rating:5.0,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;